function init_function(name)
end

function exit_function()
end

node_keys = { "seamark:type" }
way_keys = { "seamark:type" }

function split(string, delimiter)
    local fields = {}
    for field in string:gmatch("([^" .. delimiter .. "]+)") do
        fields[#fields + 1] = field
    end
    return fields
end

function process_seamark(is_way)
    local type = Find("seamark:type")
    if type == "" then return end
    type = string.lower(type)
    type = string.gsub(type, " ", "_")

    local handlers = {
        ["anchor_berth"] = function()
            Layer("anchor_berth", is_way)
            Attribute("type", "anchor_berth")
            Attribute("category", Find("seamark:anchor_berth:category"))
            Attribute("danger_class", Find("seamark:anchor_berth:danger_class"))
            Attribute("minimum_depth", Find("seamark:anchor_berth:minimum_depth"))
            Attribute("name", Find("seamark:anchor_berth:name"))
            Attribute("radius", Find("seamark:anchor_berth:radius"))
            Attribute("radius_units", Find("seamark:anchor_berth:radius:units"))
            Attribute("restriction", Find("seamark:anchor_berth:restriction"))
            Attribute("status", Find("seamark:anchor_berth:status"))
            Attribute("name", Find("seamark:name"))
        end,
        ["anchorage"] = function()
            Layer("anchorage", is_way)
            Attribute("type", "anchorage")
            Attribute("category", Find("seamark:anchorage:category"))
            Attribute("danger_class", Find("seamark:anchorage:danger_class"))
            Attribute("maximum_depth", Find("seamark:anchorage:maximum_depth"))
            Attribute("minimum_depth", Find("seamark:anchorage:minimum_depth"))
            Attribute("name", Find("seamark:anchorage:name"))
            Attribute("period_end", Find("seamark:anchorage:period_end"))
            Attribute("period_start", Find("seamark:anchorage:period_start"))
            Attribute("radius", Find("seamark:anchorage:radius"))
            Attribute("restriction", Find("seamark:anchorage:restriction"))
            Attribute("status", Find("seamark:anchorage:status"))
            Attribute("surface", Find("seamark:anchorage:surface"))
            Attribute("name", Find("seamark:name"))
        end,
        ["beacon"] = function()
            Layer("beacon", false)
            Attribute("type", "beacon")
            Attribute("colour", Find("seamark:beacon:colour"))
            Attribute("colour_pattern", Find("seamark:beacon:colour_pattern"))
            Attribute("construction", Find("seamark:beacon:construction"))
            Attribute("height", Find("seamark:beacon:height"))
            Attribute("shape", Find("seamark:beacon:shape"))
            Attribute("name", Find("seamark:name"))
        end,
        ["beacon_cardinal"] = function()
            Layer("beacon", false)
            Attribute("type", "beacon_cardinal")
            Attribute("category", Find("seamark:beacon_cardinal:category"))
            Attribute("colour", Find("seamark:beacon_cardinal:colour"))
            Attribute("colour_pattern", Find("seamark:beacon_cardinal:colour_pattern"))
            Attribute("construction", Find("seamark:beacon_cardinal:construction"))
            Attribute("elevation", Find("seamark:beacon_cardinal:elevation"))
            Attribute("height", Find("seamark:beacon_cardinal:height"))
            Attribute("period_end", Find("seamark:beacon_cardinal:period_end"))
            Attribute("period_start", Find("seamark:beacon_cardinal:period_start"))
            Attribute("reflectivity", Find("seamark:beacon_cardinal:reflectivity"))
            Attribute("shape", Find("seamark:beacon_cardinal:shape"))
            Attribute("shape_system", Find("seamark:beacon_cardinal:shape:system"))
            Attribute("status", Find("seamark:beacon_cardinal:status"))
            Attribute("name", Find("seamark:name"))
        end,
        ["beacon_isolated_danger"] = function()
            Layer("beacon", false)
            Attribute("type", "beacon_isolated_danger")
            Attribute("categroy", Find("seamark:beacon_isolated_danger:categroy"))
            Attribute("colour", Find("seamark:beacon_isolated_danger:colour"))
            Attribute("colour_pattern", Find("seamark:beacon_isolated_danger:colour_pattern"))
            Attribute("conspicuity", Find("seamark:beacon_isolated_danger:conspicuity"))
            Attribute("construction", Find("seamark:beacon_isolated_danger:construction"))
            Attribute("depth", Find("seamark:beacon_isolated_danger:depth"))
            Attribute("height", Find("seamark:beacon_isolated_danger:height"))
            Attribute("pattern", Find("seamark:beacon_isolated_danger:pattern"))
            Attribute("shape", Find("seamark:beacon_isolated_danger:shape"))
            Attribute("status", Find("seamark:beacon_isolated_danger:status"))
            Attribute("vertical_length", Find("seamark:beacon_isolated_danger:vertical_length"))
            Attribute("name", Find("seamark:name"))
        end,
        ["beacon_lateral"] = function()
            Layer("beacon", false)
            Attribute("type", "beacon_lateral")
            Attribute("category", Find("seamark:beacon_lateral:category"))
            Attribute("colour", Find("seamark:beacon_lateral:colour"))
            Attribute("colour_pattern", Find("seamark:beacon_lateral:colour_pattern"))
            Attribute("conspicuity", Find("seamark:beacon_lateral:conspicuity"))
            Attribute("construction", Find("seamark:beacon_lateral:construction"))
            Attribute("depth", Find("seamark:beacon_lateral:depth"))
            Attribute("elevation", Find("seamark:beacon_lateral:elevation"))
            Attribute("height", Find("seamark:beacon_lateral:height"))
            Attribute("impact", Find("seamark:beacon_lateral:impact"))
            Attribute("information", Find("seamark:beacon_lateral:information"))
            Attribute("national_information", Find("seamark:beacon_lateral:national_information"))
            Attribute("period_end", Find("seamark:beacon_lateral:period_end"))
            Attribute("period_start", Find("seamark:beacon_lateral:period_start"))
            Attribute("ref", Find("seamark:beacon_lateral:ref"))
            Attribute("reflectivity", Find("seamark:beacon_lateral:reflectivity"))
            Attribute("shape", Find("seamark:beacon_lateral:shape"))
            Attribute("source", Find("seamark:beacon_lateral:source"))
            Attribute("source_date", Find("seamark:beacon_lateral:source_date"))
            Attribute("status", Find("seamark:beacon_lateral:status"))
            Attribute("system", Find("seamark:beacon_lateral:system"))
            Attribute("vertical_length", Find("seamark:beacon_lateral:vertical_length"))
            Attribute("name", Find("seamark:name"))
        end,
        ["beacon_safe_water"] = function()
            Layer("beacon", is_way)
            Attribute("type", "beacon_safe_water")
            Attribute("colour", Find("seamark:beacon_safe_water:colour"))
            Attribute("colour_pattern", Find("seamark:beacon_safe_water:colour_pattern"))
            Attribute("construction", Find("seamark:beacon_safe_water:construction"))
            Attribute("shape", Find("seamark:beacon_safe_water:shape"))
            Attribute("name", Find("seamark:name"))
        end,
        ["beacon_special_purpose"] = function()
            Layer("beacon", false)
            Attribute("type", "beacon_special_purpose")
            Attribute("category", Find("seamark:beacon_special_purpose:category"))
            Attribute("colour", Find("seamark:beacon_special_purpose:colour"))
            Attribute("colour_pattern", Find("seamark:beacon_special_purpose:colour_pattern"))
            Attribute("conspicuity", Find("seamark:beacon_special_purpose:conspicuity"))
            Attribute("construction", Find("seamark:beacon_special_purpose:construction"))
            Attribute("depth", Find("seamark:beacon_special_purpose:depth"))
            Attribute("elevation", Find("seamark:beacon_special_purpose:elevation"))
            Attribute("function", Find("seamark:beacon_special_purpose:function"))
            Attribute("height", Find("seamark:beacon_special_purpose:height"))
            Attribute("information", Find("seamark:beacon_special_purpose:information"))
            Attribute("material", Find("seamark:beacon_special_purpose:material"))
            Attribute("national_information", Find("seamark:beacon_special_purpose:national_information"))
            Attribute("period_end", Find("seamark:beacon_special_purpose:period_end"))
            Attribute("period_start", Find("seamark:beacon_special_purpose:period_start"))
            Attribute("ref", Find("seamark:beacon_special_purpose:ref"))
            Attribute("reference", Find("seamark:beacon_special_purpose:reference"))
            Attribute("reflectivity", Find("seamark:beacon_special_purpose:reflectivity"))
            Attribute("shape", Find("seamark:beacon_special_purpose:shape"))
            Attribute("source", Find("seamark:beacon_special_purpose:source"))
            Attribute("source_date", Find("seamark:beacon_special_purpose:source_date"))
            Attribute("status", Find("seamark:beacon_special_purpose:status"))
            Attribute("system", Find("seamark:beacon_special_purpose:system"))
            Attribute("vertical_length", Find("seamark:beacon_special_purpose:vertical_length"))
            Attribute("name", Find("seamark:name"))
        end,
        ["berth"] = function()
            Layer("berth", is_way)
            Attribute("type", "berth")
            Attribute("category", Find("seamark:berth:category"))
            Attribute("class", Find("seamark:berth:class"))
            Attribute("clearance_length", Find("seamark:berth:clearance_length"))
            Attribute("clearance_width", Find("seamark:berth:clearance_width"))
            Attribute("danger_class", Find("seamark:berth:danger_class"))
            Attribute("goods", Find("seamark:berth:goods"))
            Attribute("information", Find("seamark:berth:information"))
            Attribute("maximum_depth", Find("seamark:berth:maximum_depth"))
            Attribute("minimum_depth", Find("seamark:berth:minimum_depth"))
            Attribute("name", Find("seamark:berth:name"))
            Attribute("restriction", Find("seamark:berth:restriction"))
            Attribute("vertical_datum", Find("seamark:berth:vertical_datum"))
            Attribute("name", Find("seamark:name"))
        end,
        ["boat_hoist"] = function()
            Layer("boat_hoist", false)
            Attribute("type", "boat_hoist")
            Attribute("name", Find("seamark:name"))
        end,
        ["bridge"] = function()
            Layer("bridge", false)
            Attribute("type", "bridge")
            Attribute("2_category", Find("seamark:bridge:2:category"))
            Attribute("2_clearance_height", Find("seamark:bridge:2:clearance_height"))
            Attribute("2_clearance_width", Find("seamark:bridge:2:clearance_width"))
            Attribute("callsign", Find("seamark:bridge:callsign"))
            Attribute("category", Find("seamark:bridge:category"))
            Attribute("channel", Find("seamark:bridge:channel"))
            Attribute("clearance_height", Find("seamark:bridge:clearance_height"))
            Attribute("clearance_height_units", Find("seamark:bridge:clearance_height:units"))
            Attribute("clearance_height_closed", Find("seamark:bridge:clearance_height_closed"))
            Attribute("clearance_height_open", Find("seamark:bridge:clearance_height_open"))
            Attribute("clearance_height_safe", Find("seamark:bridge:clearance_height_safe"))
            Attribute("clearance_width", Find("seamark:bridge:clearance_width"))
            Attribute("clearance_width_units", Find("seamark:bridge:clearance_width:units"))
            Attribute("colour", Find("seamark:bridge:colour"))
            Attribute("condition", Find("seamark:bridge:condition"))
            Attribute("conspicuity", Find("seamark:bridge:conspicuity"))
            Attribute("construction", Find("seamark:bridge:construction"))
            Attribute("name", Find("seamark:bridge:name"))
            Attribute("units", Find("seamark:bridge:units"))
            Attribute("vertical_datum", Find("seamark:bridge:vertical_datum"))
            Attribute("name", Find("seamark:name"))
        end,
        ["bunker_station"] = function()
            Layer("bunker_station", is_way)
            Attribute("type", "bunker_station")
            Attribute("category", Find("seamark:bunker_station:category"))
            Attribute("name", Find("seamark:name"))
        end,
        ["buoy"] = function()
            Layer("buoy", false)
            Attribute("type", "buoy")
            Attribute("colour", Find("seamark:buoy:colour"))
            Attribute("name", Find("seamark:name"))
        end,
        ["buoy_cardinal"] = function()
            Layer("buoy", false)
            Attribute("type", "buoy_cardinal")
            Attribute("category", Find("seamark:buoy_cardinal:category"))
            Attribute("colour", Find("seamark:buoy_cardinal:colour"))
            Attribute("colour_pattern", Find("seamark:buoy_cardinal:colour_pattern"))
            Attribute("depth", Find("seamark:buoy_cardinal:depth"))
            Attribute("period_end", Find("seamark:buoy_cardinal:period_end"))
            Attribute("period_start", Find("seamark:buoy_cardinal:period_start"))
            Attribute("ref", Find("seamark:buoy_cardinal:ref"))
            Attribute("reflectivity", Find("seamark:buoy_cardinal:reflectivity"))
            Attribute("shape", Find("seamark:buoy_cardinal:shape"))
            Attribute("shape_system", Find("seamark:buoy_cardinal:shape:system"))
            Attribute("source", Find("seamark:buoy_cardinal:source"))
            Attribute("source_date", Find("seamark:buoy_cardinal:source_date"))
            Attribute("status", Find("seamark:buoy_cardinal:status"))
            Attribute("system", Find("seamark:buoy_cardinal:system"))
            Attribute("name", Find("seamark:name"))
        end,
        ["buoy_cardinal_n"] = function()
            Layer("buoy", false)
            Attribute("type", "buoy_cardinal_n")
            Attribute("name", Find("seamark:name"))
        end,
        ["buoy_cardinal_s"] = function()
            Layer("buoy", false)
            Attribute("type", "buoy_cardinal_s")
            Attribute("name", Find("seamark:name"))
        end,
        ["buoy_installation"] = function()
            Layer("buoy", false)
            Attribute("type", "buoy_installation")
            Attribute("category", Find("seamark:buoy_installation:category"))
            Attribute("colour", Find("seamark:buoy_installation:colour"))
            Attribute("colour_pattern", Find("seamark:buoy_installation:colour_pattern"))
            Attribute("reflectivity", Find("seamark:buoy_installation:reflectivity"))
            Attribute("shape", Find("seamark:buoy_installation:shape"))
            Attribute("name", Find("seamark:name"))
        end,
        ["buoy_isolated_danger"] = function()
            Layer("buoy", false)
            Attribute("type", "buoy_isolated_danger")
            Attribute("colour", Find("seamark:buoy_isolated_danger:colour"))
            Attribute("colour_pattern", Find("seamark:buoy_isolated_danger:colour_pattern"))
            Attribute("information", Find("seamark:buoy_isolated_danger:information"))
            Attribute("ref", Find("seamark:buoy_isolated_danger:ref"))
            Attribute("shape", Find("seamark:buoy_isolated_danger:shape"))
            Attribute("source", Find("seamark:buoy_isolated_danger:source"))
            Attribute("source_date", Find("seamark:buoy_isolated_danger:source_date"))
            Attribute("status", Find("seamark:buoy_isolated_danger:status"))
            Attribute("name", Find("seamark:name"))
        end,
        ["buoy_lateral"] = function()
            Layer("buoy", false)
            Attribute("type", "buoy_lateral")
            Attribute("category", Find("seamark:buoy_lateral:category"))
            Attribute("colour", Find("seamark:buoy_lateral:colour"))
            Attribute("colour_pattern", Find("seamark:buoy_lateral:colour_pattern"))
            Attribute("conspicuity", Find("seamark:buoy_lateral:conspicuity"))
            Attribute("construction", Find("seamark:buoy_lateral:construction"))
            Attribute("depth", Find("seamark:buoy_lateral:depth"))
            Attribute("elevation", Find("seamark:buoy_lateral:elevation"))
            Attribute("group", Find("seamark:buoy_lateral:group"))
            Attribute("height", Find("seamark:buoy_lateral:height"))
            Attribute("information", Find("seamark:buoy_lateral:information"))
            Attribute("name", Find("seamark:buoy_lateral:name"))
            Attribute("period_end", Find("seamark:buoy_lateral:period_end"))
            Attribute("period_start", Find("seamark:buoy_lateral:period_start"))
            Attribute("ref", Find("seamark:buoy_lateral:ref"))
            Attribute("reflectivity", Find("seamark:buoy_lateral:reflectivity"))
            Attribute("shape", Find("seamark:buoy_lateral:shape"))
            Attribute("source", Find("seamark:buoy_lateral:source"))
            Attribute("source_date", Find("seamark:buoy_lateral:source_date"))
            Attribute("status", Find("seamark:buoy_lateral:status"))
            Attribute("system", Find("seamark:buoy_lateral:system"))
            Attribute("vertical_length", Find("seamark:buoy_lateral:vertical_length"))
            Attribute("name", Find("seamark:name"))
        end,
        ["buoy_safe_water"] = function()
            Layer("buoy", is_way)
            Attribute("type", "buoy_safe_water")
            Attribute("category", Find("seamark:buoy_safe_water:category"))
            Attribute("colour", Find("seamark:buoy_safe_water:colour"))
            Attribute("colour_pattern", Find("seamark:buoy_safe_water:colour_pattern"))
            Attribute("information", Find("seamark:buoy_safe_water:information"))
            Attribute("period_end", Find("seamark:buoy_safe_water:period_end"))
            Attribute("period_start", Find("seamark:buoy_safe_water:period_start"))
            Attribute("ref", Find("seamark:buoy_safe_water:ref"))
            Attribute("shape", Find("seamark:buoy_safe_water:shape"))
            Attribute("source", Find("seamark:buoy_safe_water:source"))
            Attribute("source_date", Find("seamark:buoy_safe_water:source_date"))
            Attribute("status", Find("seamark:buoy_safe_water:status"))
            Attribute("system", Find("seamark:buoy_safe_water:system"))
            Attribute("name", Find("seamark:name"))
        end,
        ["buoy_special_purpose"] = function()
            Layer("buoy", false)
            Attribute("type", "buoy_special_purpose")
            Attribute("category", Find("seamark:buoy_special_purpose:category"))
            Attribute("colour", Find("seamark:buoy_special_purpose:colour"))
            Attribute("colour_pattern", Find("seamark:buoy_special_purpose:colour_pattern"))
            Attribute("construction", Find("seamark:buoy_special_purpose:construction"))
            Attribute("depth", Find("seamark:buoy_special_purpose:depth"))
            Attribute("information", Find("seamark:buoy_special_purpose:information"))
            Attribute("period_end", Find("seamark:buoy_special_purpose:period_end"))
            Attribute("period_start", Find("seamark:buoy_special_purpose:period_start"))
            Attribute("ref", Find("seamark:buoy_special_purpose:ref"))
            Attribute("reflectivity", Find("seamark:buoy_special_purpose:reflectivity"))
            Attribute("shape", Find("seamark:buoy_special_purpose:shape"))
            Attribute("source", Find("seamark:buoy_special_purpose:source"))
            Attribute("source_date", Find("seamark:buoy_special_purpose:source_date"))
            Attribute("status", Find("seamark:buoy_special_purpose:status"))
            Attribute("system", Find("seamark:buoy_special_purpose:system"))
            Attribute("name", Find("seamark:name"))
        end,
        ["cable_area"] = function()
            Layer("cable", is_way)
            Attribute("type", "cable_area")
            Attribute("category", Find("seamark:cable_area:category"))
            Attribute("clearance_height_safe", Find("seamark:cable_area:clearance_height_safe"))
            Attribute("restriction", Find("seamark:cable_area:restriction"))
            Attribute("name", Find("seamark:name"))
        end,
        ["cable_overhead"] = function()
            Layer("cable", false)
            Attribute("type", "cable_overhead")
            Attribute("category", Find("seamark:cable_overhead:category"))
            Attribute("clearance_height", Find("seamark:cable_overhead:clearance_height"))
            Attribute("clearance_height_safe", Find("seamark:cable_overhead:clearance_height_safe"))
            Attribute("clearance_height_safe_units", Find("seamark:cable_overhead:clearance_height_safe:units"))
            Attribute("clearance_width", Find("seamark:cable_overhead:clearance_width"))
            Attribute("vertical_clearance_safe", Find("seamark:cable_overhead:vertical_clearance_safe"))
            Attribute("name", Find("seamark:name"))
        end,
        ["cable_submarine"] = function()
            Layer("cable", false)
            Attribute("type", "cable_submarine")
            Attribute("category", Find("seamark:cable_submarine:category"))
            Attribute("condition", Find("seamark:cable_submarine:condition"))
            Attribute("depth_buried", Find("seamark:cable_submarine:depth_buried"))
            Attribute("name", Find("seamark:cable_submarine:name"))
            Attribute("restriction", Find("seamark:cable_submarine:restriction"))
            Attribute("status", Find("seamark:cable_submarine:status"))
            Attribute("name", Find("seamark:name"))
        end,
        ["causeway"] = function()
            Layer("causeway", is_way)
            Attribute("type", "causeway")
            Attribute("water_level", Find("seamark:causeway:water_level"))
            Attribute("name", Find("seamark:name"))
        end,
        ["coastguard_station"] = function()
            Layer("coastguard", is_way)
            Attribute("type", "coastguard_station")
            Attribute("channel", Find("seamark:coastguard_station:channel"))
            Attribute("name", Find("seamark:name"))
        end,
        ["conveyor"] = function()
            Layer("conveyor", false)
            Attribute("type", "conveyor")
            Attribute("category", Find("seamark:conveyor:category"))
            Attribute("clearance_height", Find("seamark:conveyor:clearance_height"))
            Attribute("name", Find("seamark:name"))
        end,
        ["distance_mark"] = function()
            Layer("distance_mark", false)
            Attribute("type", "distance_mark")
            Attribute("category", Find("seamark:distance_mark:category"))
            Attribute("distance", Find("seamark:distance_mark:distance"))
            Attribute("units", Find("seamark:distance_mark:units"))
            Attribute("name", Find("seamark:name"))
        end,
        ["dredged_area"] = function()
            Layer("dredged_area", is_way)
            Attribute("type", "dredged_area")
            Attribute("minimum_depth", Find("seamark:dredged_area:minimum_depth"))
            Attribute("name", Find("seamark:name"))
        end,
        ["dry_dock"] = function()
            Layer("dry_dock", is_way)
            Attribute("type", "dry_dock")
            Attribute("name", Find("seamark:name"))
        end,
        ["dumping_ground"] = function()
            Layer("dumping_ground", is_way)
            Attribute("type", "dumping_ground")
            Attribute("category", Find("seamark:dumping_ground:category"))
            Attribute("restriction", Find("seamark:dumping_ground:restriction"))
            Attribute("status", Find("seamark:dumping_ground:status"))
            Attribute("name", Find("seamark:name"))
        end,
        ["exceptional_structure"] = function()
            Layer("exceptional_structure", is_way)
            Attribute("type", "exceptional_structure")
            Attribute("category", Find("seamark:exceptional_structure:category"))
            Attribute("name", Find("seamark:name"))
        end,
        ["fairway"] = function()
            Layer("fairway", is_way)
            Attribute("type", "fairway")
            Attribute("information", Find("seamark:fairway:information"))
            Attribute("minimum_depth", Find("seamark:fairway:minimum_depth"))
            Attribute("orientation", Find("seamark:fairway:orientation"))
            Attribute("restriction", Find("seamark:fairway:restriction"))
            Attribute("name", Find("seamark:name"))
        end,
        ["ferry_route"] = function()
            Layer("ferry", false)
            Attribute("type", "ferry_route")
            Attribute("category", Find("seamark:ferry_route:category"))
            Attribute("name", Find("seamark:name"))
        end,
        ["fishing_facility"] = function()
            Layer("fishing_facility", is_way)
            Attribute("type", "fishing_facility")
            Attribute("category", Find("seamark:fishing_facility:category"))
            Attribute("name", Find("seamark:name"))
        end,
        ["floating_dock"] = function()
            Layer("floating_dock", is_way)
            Attribute("type", "floating_dock")
            Attribute("name", Find("seamark:name"))
        end,
        ["fog_signal"] = function()
            Layer("fog_signal", false)
            Attribute("type", "fog_signal")
            Attribute("category", Find("seamark:fog_signal:category"))
            Attribute("frequency", Find("seamark:fog_signal:frequency"))
            Attribute("generation", Find("seamark:fog_signal:generation"))
            Attribute("group", Find("seamark:fog_signal:group"))
            Attribute("information", Find("seamark:fog_signal:information"))
            Attribute("period", Find("seamark:fog_signal:period"))
            Attribute("range", Find("seamark:fog_signal:range"))
            Attribute("ref", Find("seamark:fog_signal:ref"))
            Attribute("reference", Find("seamark:fog_signal:reference"))
            Attribute("sequence", Find("seamark:fog_signal:sequence"))
            Attribute("source", Find("seamark:fog_signal:source"))
            Attribute("source_date", Find("seamark:fog_signal:source_date"))
            Attribute("status", Find("seamark:fog_signal:status"))
            Attribute("name", Find("seamark:name"))
        end,
        ["fortified_structure"] = function()
            Layer("fortified_structure", is_way)
            Attribute("type", "fortified_structure")
            Attribute("category", Find("seamark:fortified_structure:category"))
            Attribute("name", Find("seamark:name"))
        end,
        ["gate"] = function()
            Layer("gate", is_way)
            Attribute("type", "gate")
            Attribute("category", Find("seamark:gate:category"))
            Attribute("clearance_height", Find("seamark:gate:clearance_height"))
            Attribute("clearance_height_closed", Find("seamark:gate:clearance_height_closed"))
            Attribute("clearance_height_open", Find("seamark:gate:clearance_height_open"))
            Attribute("clearance_width", Find("seamark:gate:clearance_width"))
            Attribute("condition", Find("seamark:gate:condition"))
            Attribute("minimum_depth", Find("seamark:gate:minimum_depth"))
            Attribute("vertical_datum", Find("seamark:gate:vertical_datum"))
            Attribute("water_level", Find("seamark:gate:water_level"))
            Attribute("name", Find("seamark:name"))
        end,
        ["gridiron"] = function()
            Layer("gridiron", is_way)
            Attribute("type", "gridiron")
            Attribute("name", Find("seamark:name"))
        end,
        ["harbour"] = function()
            Layer("harbour", is_way)
            Attribute("type", "harbour")
            Attribute("category", Find("seamark:harbour:category"))
            Attribute("name", Find("seamark:harbour:name"))
            Attribute("restriction", Find("seamark:harbour:restriction"))
            Attribute("type", Find("seamark:harbour:type"))
            Attribute("name", Find("seamark:name"))
        end,
        ["harbour_basin"] = function()
            Layer("harbour_basin", is_way)
            Attribute("type", "harbour_basin")
            Attribute("restriction", Find("seamark:harbour_basin:restriction"))
            Attribute("name", Find("seamark:name"))
        end,
        ["harbour_limit"] = function()
            Layer("harbour_limit", is_way)
            Attribute("type", "harbour_limit")
            Attribute("name", Find("seamark:name"))
        end,
        ["hazard"] = function()
            Layer("hazard", false)
            Attribute("type", "hazard")
            Attribute("name", Find("seamark:name"))
        end,
        ["hulk"] = function()
            Layer("hulk", is_way)
            Attribute("type", "hulk")
            Attribute("category", Find("seamark:hulk:category"))
            Attribute("name", Find("seamark:name"))
        end,
        ["landmark"] = function()
            Layer("landmark", is_way)
            Attribute("type", "landmark")
            Attribute("category", Find("seamark:landmark:category"))
            Attribute("colour", Find("seamark:landmark:colour"))
            Attribute("colour_pattern", Find("seamark:landmark:colour_pattern"))
            Attribute("condition", Find("seamark:landmark:condition"))
            Attribute("conspicuity", Find("seamark:landmark:conspicuity"))
            Attribute("construction", Find("seamark:landmark:construction"))
            Attribute("elevation", Find("seamark:landmark:elevation"))
            Attribute("function", Find("seamark:landmark:function"))
            Attribute("height", Find("seamark:landmark:height"))
            Attribute("information", Find("seamark:landmark:information"))
            Attribute("name", Find("seamark:landmark:name"))
            Attribute("ref", Find("seamark:landmark:ref"))
            Attribute("reference", Find("seamark:landmark:reference"))
            Attribute("reflectivity", Find("seamark:landmark:reflectivity"))
            Attribute("source", Find("seamark:landmark:source"))
            Attribute("source_date", Find("seamark:landmark:source_date"))
            Attribute("status", Find("seamark:landmark:status"))
            Attribute("vertical_length", Find("seamark:landmark:vertical_length"))
            Attribute("name", Find("seamark:name"))
        end,
        ["leading_line"] = function()
            Layer("leading_line", false)
            Attribute("type", "leading_line")
            Attribute("name", Find("seamark:name"))
        end,
        ["leading_mark"] = function()
            Layer("leading_mark", false)
            Attribute("type", "leading_mark")
            Attribute("name", Find("seamark:name"))
        end,
        ["light"] = function()
            Layer("light", false)
            Attribute("type", "light")
            Attribute("10_category", Find("seamark:light:10:category"))
            Attribute("10_character", Find("seamark:light:10:character"))
            Attribute("10_colour", Find("seamark:light:10:colour"))
            Attribute("10_exhibition", Find("seamark:light:10:exhibition"))
            Attribute("10_group", Find("seamark:light:10:group"))
            Attribute("10_height", Find("seamark:light:10:height"))
            Attribute("10_national_information", Find("seamark:light:10:national_information"))
            Attribute("10_orientation", Find("seamark:light:10:orientation"))
            Attribute("10_period", Find("seamark:light:10:period"))
            Attribute("10_range", Find("seamark:light:10:range"))
            Attribute("10_sector_end", Find("seamark:light:10:sector_end"))
            Attribute("10_sector_start", Find("seamark:light:10:sector_start"))
            Attribute("10_sequence", Find("seamark:light:10:sequence"))
            Attribute("10_vertical_datum", Find("seamark:light:10:vertical_datum"))
            Attribute("10_visibility", Find("seamark:light:10:visibility"))
            Attribute("11_category", Find("seamark:light:11:category"))
            Attribute("11_character", Find("seamark:light:11:character"))
            Attribute("11_colour", Find("seamark:light:11:colour"))
            Attribute("11_exhibition", Find("seamark:light:11:exhibition"))
            Attribute("11_group", Find("seamark:light:11:group"))
            Attribute("11_height", Find("seamark:light:11:height"))
            Attribute("11_national_information", Find("seamark:light:11:national_information"))
            Attribute("11_period", Find("seamark:light:11:period"))
            Attribute("11_range", Find("seamark:light:11:range"))
            Attribute("11_sector_end", Find("seamark:light:11:sector_end"))
            Attribute("11_sector_start", Find("seamark:light:11:sector_start"))
            Attribute("11_sequence", Find("seamark:light:11:sequence"))
            Attribute("11_vertical_datum", Find("seamark:light:11:vertical_datum"))
            Attribute("11_visibility", Find("seamark:light:11:visibility"))
            Attribute("12_category", Find("seamark:light:12:category"))
            Attribute("12_character", Find("seamark:light:12:character"))
            Attribute("12_colour", Find("seamark:light:12:colour"))
            Attribute("12_exhibition", Find("seamark:light:12:exhibition"))
            Attribute("12_group", Find("seamark:light:12:group"))
            Attribute("12_height", Find("seamark:light:12:height"))
            Attribute("12_national_information", Find("seamark:light:12:national_information"))
            Attribute("12_period", Find("seamark:light:12:period"))
            Attribute("12_range", Find("seamark:light:12:range"))
            Attribute("12_sector_end", Find("seamark:light:12:sector_end"))
            Attribute("12_sector_start", Find("seamark:light:12:sector_start"))
            Attribute("12_sequence", Find("seamark:light:12:sequence"))
            Attribute("12_vertical_datum", Find("seamark:light:12:vertical_datum"))
            Attribute("12_visibility", Find("seamark:light:12:visibility"))
            Attribute("13_category", Find("seamark:light:13:category"))
            Attribute("13_character", Find("seamark:light:13:character"))
            Attribute("13_colour", Find("seamark:light:13:colour"))
            Attribute("13_exhibition", Find("seamark:light:13:exhibition"))
            Attribute("13_group", Find("seamark:light:13:group"))
            Attribute("13_height", Find("seamark:light:13:height"))
            Attribute("13_national_information", Find("seamark:light:13:national_information"))
            Attribute("13_period", Find("seamark:light:13:period"))
            Attribute("13_range", Find("seamark:light:13:range"))
            Attribute("13_sector_end", Find("seamark:light:13:sector_end"))
            Attribute("13_sector_start", Find("seamark:light:13:sector_start"))
            Attribute("13_sequence", Find("seamark:light:13:sequence"))
            Attribute("13_vertical_datum", Find("seamark:light:13:vertical_datum"))
            Attribute("14_category", Find("seamark:light:14:category"))
            Attribute("14_character", Find("seamark:light:14:character"))
            Attribute("14_colour", Find("seamark:light:14:colour"))
            Attribute("14_exhibition", Find("seamark:light:14:exhibition"))
            Attribute("14_group", Find("seamark:light:14:group"))
            Attribute("14_height", Find("seamark:light:14:height"))
            Attribute("14_national_information", Find("seamark:light:14:national_information"))
            Attribute("14_period", Find("seamark:light:14:period"))
            Attribute("14_range", Find("seamark:light:14:range"))
            Attribute("14_sector_end", Find("seamark:light:14:sector_end"))
            Attribute("14_sector_start", Find("seamark:light:14:sector_start"))
            Attribute("14_sequence", Find("seamark:light:14:sequence"))
            Attribute("15_character", Find("seamark:light:15:character"))
            Attribute("15_colour", Find("seamark:light:15:colour"))
            Attribute("15_exhibition", Find("seamark:light:15:exhibition"))
            Attribute("15_group", Find("seamark:light:15:group"))
            Attribute("15_height", Find("seamark:light:15:height"))
            Attribute("15_national_information", Find("seamark:light:15:national_information"))
            Attribute("15_period", Find("seamark:light:15:period"))
            Attribute("15_range", Find("seamark:light:15:range"))
            Attribute("15_sector_end", Find("seamark:light:15:sector_end"))
            Attribute("15_sector_start", Find("seamark:light:15:sector_start"))
            Attribute("15_sequence", Find("seamark:light:15:sequence"))
            Attribute("16_category", Find("seamark:light:16:category"))
            Attribute("16_character", Find("seamark:light:16:character"))
            Attribute("16_colour", Find("seamark:light:16:colour"))
            Attribute("16_exhibition", Find("seamark:light:16:exhibition"))
            Attribute("16_group", Find("seamark:light:16:group"))
            Attribute("16_height", Find("seamark:light:16:height"))
            Attribute("16_national_information", Find("seamark:light:16:national_information"))
            Attribute("16_period", Find("seamark:light:16:period"))
            Attribute("16_range", Find("seamark:light:16:range"))
            Attribute("16_sector_end", Find("seamark:light:16:sector_end"))
            Attribute("16_sector_start", Find("seamark:light:16:sector_start"))
            Attribute("16_sequence", Find("seamark:light:16:sequence"))
            Attribute("17_category", Find("seamark:light:17:category"))
            Attribute("17_character", Find("seamark:light:17:character"))
            Attribute("17_colour", Find("seamark:light:17:colour"))
            Attribute("17_exhibition", Find("seamark:light:17:exhibition"))
            Attribute("17_group", Find("seamark:light:17:group"))
            Attribute("17_height", Find("seamark:light:17:height"))
            Attribute("17_national_information", Find("seamark:light:17:national_information"))
            Attribute("17_period", Find("seamark:light:17:period"))
            Attribute("17_range", Find("seamark:light:17:range"))
            Attribute("17_sector_end", Find("seamark:light:17:sector_end"))
            Attribute("17_sector_start", Find("seamark:light:17:sector_start"))
            Attribute("17_sequence", Find("seamark:light:17:sequence"))
            Attribute("18_character", Find("seamark:light:18:character"))
            Attribute("18_colour", Find("seamark:light:18:colour"))
            Attribute("18_exhibition", Find("seamark:light:18:exhibition"))
            Attribute("18_group", Find("seamark:light:18:group"))
            Attribute("18_height", Find("seamark:light:18:height"))
            Attribute("18_national_information", Find("seamark:light:18:national_information"))
            Attribute("18_period", Find("seamark:light:18:period"))
            Attribute("18_range", Find("seamark:light:18:range"))
            Attribute("18_sector_end", Find("seamark:light:18:sector_end"))
            Attribute("18_sector_start", Find("seamark:light:18:sector_start"))
            Attribute("18_sequence", Find("seamark:light:18:sequence"))
            Attribute("19_category", Find("seamark:light:19:category"))
            Attribute("19_character", Find("seamark:light:19:character"))
            Attribute("19_colour", Find("seamark:light:19:colour"))
            Attribute("19_group", Find("seamark:light:19:group"))
            Attribute("19_height", Find("seamark:light:19:height"))
            Attribute("19_national_information", Find("seamark:light:19:national_information"))
            Attribute("19_period", Find("seamark:light:19:period"))
            Attribute("19_range", Find("seamark:light:19:range"))
            Attribute("19_sector_end", Find("seamark:light:19:sector_end"))
            Attribute("19_sector_start", Find("seamark:light:19:sector_start"))
            Attribute("19_sequence", Find("seamark:light:19:sequence"))
            Attribute("1_category", Find("seamark:light:1:category"))
            Attribute("1_character", Find("seamark:light:1:character"))
            Attribute("1_colour", Find("seamark:light:1:colour"))
            Attribute("1_exhibition", Find("seamark:light:1:exhibition"))
            Attribute("1_group", Find("seamark:light:1:group"))
            Attribute("1_height", Find("seamark:light:1:height"))
            Attribute("1_information", Find("seamark:light:1:information"))
            Attribute("1_multiple", Find("seamark:light:1:multiple"))
            Attribute("1_national_information", Find("seamark:light:1:national_information"))
            Attribute("1_note", Find("seamark:light:1:note"))
            Attribute("1_orientation", Find("seamark:light:1:orientation"))
            Attribute("1_period", Find("seamark:light:1:period"))
            Attribute("1_range", Find("seamark:light:1:range"))
            Attribute("1_reference", Find("seamark:light:1:reference"))
            Attribute("1_sector_end", Find("seamark:light:1:sector_end"))
            Attribute("1_sector_start", Find("seamark:light:1:sector_start"))
            Attribute("1_sequence", Find("seamark:light:1:sequence"))
            Attribute("1_status", Find("seamark:light:1:status"))
            Attribute("1_vertical_datum", Find("seamark:light:1:vertical_datum"))
            Attribute("1_visibility", Find("seamark:light:1:visibility"))
            Attribute("20_character", Find("seamark:light:20:character"))
            Attribute("20_colour", Find("seamark:light:20:colour"))
            Attribute("20_group", Find("seamark:light:20:group"))
            Attribute("20_height", Find("seamark:light:20:height"))
            Attribute("20_national_information", Find("seamark:light:20:national_information"))
            Attribute("20_period", Find("seamark:light:20:period"))
            Attribute("20_range", Find("seamark:light:20:range"))
            Attribute("20_sector_end", Find("seamark:light:20:sector_end"))
            Attribute("20_sector_start", Find("seamark:light:20:sector_start"))
            Attribute("20_sequence", Find("seamark:light:20:sequence"))
            Attribute("21_character", Find("seamark:light:21:character"))
            Attribute("21_colour", Find("seamark:light:21:colour"))
            Attribute("21_group", Find("seamark:light:21:group"))
            Attribute("21_height", Find("seamark:light:21:height"))
            Attribute("21_national_information", Find("seamark:light:21:national_information"))
            Attribute("21_period", Find("seamark:light:21:period"))
            Attribute("21_range", Find("seamark:light:21:range"))
            Attribute("21_sector_end", Find("seamark:light:21:sector_end"))
            Attribute("21_sector_start", Find("seamark:light:21:sector_start"))
            Attribute("21_sequence", Find("seamark:light:21:sequence"))
            Attribute("22_character", Find("seamark:light:22:character"))
            Attribute("22_colour", Find("seamark:light:22:colour"))
            Attribute("22_group", Find("seamark:light:22:group"))
            Attribute("22_height", Find("seamark:light:22:height"))
            Attribute("22_national_information", Find("seamark:light:22:national_information"))
            Attribute("22_period", Find("seamark:light:22:period"))
            Attribute("22_range", Find("seamark:light:22:range"))
            Attribute("22_sector_end", Find("seamark:light:22:sector_end"))
            Attribute("22_sector_start", Find("seamark:light:22:sector_start"))
            Attribute("22_sequence", Find("seamark:light:22:sequence"))
            Attribute("23_character", Find("seamark:light:23:character"))
            Attribute("23_colour", Find("seamark:light:23:colour"))
            Attribute("23_group", Find("seamark:light:23:group"))
            Attribute("23_height", Find("seamark:light:23:height"))
            Attribute("23_national_information", Find("seamark:light:23:national_information"))
            Attribute("23_period", Find("seamark:light:23:period"))
            Attribute("23_range", Find("seamark:light:23:range"))
            Attribute("23_sector_end", Find("seamark:light:23:sector_end"))
            Attribute("23_sector_start", Find("seamark:light:23:sector_start"))
            Attribute("23_sequence", Find("seamark:light:23:sequence"))
            Attribute("24_character", Find("seamark:light:24:character"))
            Attribute("24_colour", Find("seamark:light:24:colour"))
            Attribute("24_group", Find("seamark:light:24:group"))
            Attribute("24_height", Find("seamark:light:24:height"))
            Attribute("24_national_information", Find("seamark:light:24:national_information"))
            Attribute("24_period", Find("seamark:light:24:period"))
            Attribute("24_range", Find("seamark:light:24:range"))
            Attribute("24_sector_end", Find("seamark:light:24:sector_end"))
            Attribute("24_sector_start", Find("seamark:light:24:sector_start"))
            Attribute("24_sequence", Find("seamark:light:24:sequence"))
            Attribute("25_character", Find("seamark:light:25:character"))
            Attribute("25_colour", Find("seamark:light:25:colour"))
            Attribute("25_group", Find("seamark:light:25:group"))
            Attribute("25_height", Find("seamark:light:25:height"))
            Attribute("25_national_information", Find("seamark:light:25:national_information"))
            Attribute("25_period", Find("seamark:light:25:period"))
            Attribute("25_range", Find("seamark:light:25:range"))
            Attribute("25_sector_end", Find("seamark:light:25:sector_end"))
            Attribute("25_sector_start", Find("seamark:light:25:sector_start"))
            Attribute("25_sequence", Find("seamark:light:25:sequence"))
            Attribute("26_character", Find("seamark:light:26:character"))
            Attribute("26_colour", Find("seamark:light:26:colour"))
            Attribute("26_group", Find("seamark:light:26:group"))
            Attribute("26_height", Find("seamark:light:26:height"))
            Attribute("26_national_information", Find("seamark:light:26:national_information"))
            Attribute("26_period", Find("seamark:light:26:period"))
            Attribute("26_range", Find("seamark:light:26:range"))
            Attribute("26_sector_end", Find("seamark:light:26:sector_end"))
            Attribute("26_sector_start", Find("seamark:light:26:sector_start"))
            Attribute("26_sequence", Find("seamark:light:26:sequence"))
            Attribute("27_character", Find("seamark:light:27:character"))
            Attribute("27_colour", Find("seamark:light:27:colour"))
            Attribute("27_group", Find("seamark:light:27:group"))
            Attribute("27_height", Find("seamark:light:27:height"))
            Attribute("27_national_information", Find("seamark:light:27:national_information"))
            Attribute("27_period", Find("seamark:light:27:period"))
            Attribute("27_range", Find("seamark:light:27:range"))
            Attribute("27_sector_end", Find("seamark:light:27:sector_end"))
            Attribute("27_sector_start", Find("seamark:light:27:sector_start"))
            Attribute("27_sequence", Find("seamark:light:27:sequence"))
            Attribute("2_category", Find("seamark:light:2:category"))
            Attribute("2_character", Find("seamark:light:2:character"))
            Attribute("2_colour", Find("seamark:light:2:colour"))
            Attribute("2_exhibition", Find("seamark:light:2:exhibition"))
            Attribute("2_group", Find("seamark:light:2:group"))
            Attribute("2_height", Find("seamark:light:2:height"))
            Attribute("2_information", Find("seamark:light:2:information"))
            Attribute("2_multiple", Find("seamark:light:2:multiple"))
            Attribute("2_national_information", Find("seamark:light:2:national_information"))
            Attribute("2_note", Find("seamark:light:2:note"))
            Attribute("2_orientation", Find("seamark:light:2:orientation"))
            Attribute("2_period", Find("seamark:light:2:period"))
            Attribute("2_range", Find("seamark:light:2:range"))
            Attribute("2_reference", Find("seamark:light:2:reference"))
            Attribute("2_sector_end", Find("seamark:light:2:sector_end"))
            Attribute("2_sector_start", Find("seamark:light:2:sector_start"))
            Attribute("2_sequence", Find("seamark:light:2:sequence"))
            Attribute("2_status", Find("seamark:light:2:status"))
            Attribute("2_vertical_datum", Find("seamark:light:2:vertical_datum"))
            Attribute("2_visibility", Find("seamark:light:2:visibility"))
            Attribute("3_category", Find("seamark:light:3:category"))
            Attribute("3_character", Find("seamark:light:3:character"))
            Attribute("3_colour", Find("seamark:light:3:colour"))
            Attribute("3_exhibition", Find("seamark:light:3:exhibition"))
            Attribute("3_group", Find("seamark:light:3:group"))
            Attribute("3_height", Find("seamark:light:3:height"))
            Attribute("3_multiple", Find("seamark:light:3:multiple"))
            Attribute("3_national_information", Find("seamark:light:3:national_information"))
            Attribute("3_note", Find("seamark:light:3:note"))
            Attribute("3_orientation", Find("seamark:light:3:orientation"))
            Attribute("3_period", Find("seamark:light:3:period"))
            Attribute("3_range", Find("seamark:light:3:range"))
            Attribute("3_sector_end", Find("seamark:light:3:sector_end"))
            Attribute("3_sector_start", Find("seamark:light:3:sector_start"))
            Attribute("3_sequence", Find("seamark:light:3:sequence"))
            Attribute("3_status", Find("seamark:light:3:status"))
            Attribute("3_vertical_datum", Find("seamark:light:3:vertical_datum"))
            Attribute("3_visibility", Find("seamark:light:3:visibility"))
            Attribute("4_category", Find("seamark:light:4:category"))
            Attribute("4_character", Find("seamark:light:4:character"))
            Attribute("4_colour", Find("seamark:light:4:colour"))
            Attribute("4_exhibition", Find("seamark:light:4:exhibition"))
            Attribute("4_group", Find("seamark:light:4:group"))
            Attribute("4_height", Find("seamark:light:4:height"))
            Attribute("4_national_information", Find("seamark:light:4:national_information"))
            Attribute("4_note", Find("seamark:light:4:note"))
            Attribute("4_orientation", Find("seamark:light:4:orientation"))
            Attribute("4_period", Find("seamark:light:4:period"))
            Attribute("4_range", Find("seamark:light:4:range"))
            Attribute("4_sector_end", Find("seamark:light:4:sector_end"))
            Attribute("4_sector_start", Find("seamark:light:4:sector_start"))
            Attribute("4_sequence", Find("seamark:light:4:sequence"))
            Attribute("4_vertical_datum", Find("seamark:light:4:vertical_datum"))
            Attribute("4_visibility", Find("seamark:light:4:visibility"))
            Attribute("5_category", Find("seamark:light:5:category"))
            Attribute("5_character", Find("seamark:light:5:character"))
            Attribute("5_colour", Find("seamark:light:5:colour"))
            Attribute("5_exhibition", Find("seamark:light:5:exhibition"))
            Attribute("5_group", Find("seamark:light:5:group"))
            Attribute("5_height", Find("seamark:light:5:height"))
            Attribute("5_national_information", Find("seamark:light:5:national_information"))
            Attribute("5_orientation", Find("seamark:light:5:orientation"))
            Attribute("5_period", Find("seamark:light:5:period"))
            Attribute("5_range", Find("seamark:light:5:range"))
            Attribute("5_sector_end", Find("seamark:light:5:sector_end"))
            Attribute("5_sector_start", Find("seamark:light:5:sector_start"))
            Attribute("5_sequence", Find("seamark:light:5:sequence"))
            Attribute("5_vertical_datum", Find("seamark:light:5:vertical_datum"))
            Attribute("5_visibility", Find("seamark:light:5:visibility"))
            Attribute("6_category", Find("seamark:light:6:category"))
            Attribute("6_character", Find("seamark:light:6:character"))
            Attribute("6_colour", Find("seamark:light:6:colour"))
            Attribute("6_exhibition", Find("seamark:light:6:exhibition"))
            Attribute("6_group", Find("seamark:light:6:group"))
            Attribute("6_height", Find("seamark:light:6:height"))
            Attribute("6_national_information", Find("seamark:light:6:national_information"))
            Attribute("6_orientation", Find("seamark:light:6:orientation"))
            Attribute("6_period", Find("seamark:light:6:period"))
            Attribute("6_range", Find("seamark:light:6:range"))
            Attribute("6_sector_end", Find("seamark:light:6:sector_end"))
            Attribute("6_sector_start", Find("seamark:light:6:sector_start"))
            Attribute("6_sequence", Find("seamark:light:6:sequence"))
            Attribute("6_vertical_datum", Find("seamark:light:6:vertical_datum"))
            Attribute("6_visibility", Find("seamark:light:6:visibility"))
            Attribute("7_category", Find("seamark:light:7:category"))
            Attribute("7_character", Find("seamark:light:7:character"))
            Attribute("7_colour", Find("seamark:light:7:colour"))
            Attribute("7_exhibition", Find("seamark:light:7:exhibition"))
            Attribute("7_group", Find("seamark:light:7:group"))
            Attribute("7_height", Find("seamark:light:7:height"))
            Attribute("7_national_information", Find("seamark:light:7:national_information"))
            Attribute("7_orientation", Find("seamark:light:7:orientation"))
            Attribute("7_period", Find("seamark:light:7:period"))
            Attribute("7_range", Find("seamark:light:7:range"))
            Attribute("7_sector_end", Find("seamark:light:7:sector_end"))
            Attribute("7_sector_start", Find("seamark:light:7:sector_start"))
            Attribute("7_sequence", Find("seamark:light:7:sequence"))
            Attribute("7_vertical_datum", Find("seamark:light:7:vertical_datum"))
            Attribute("7_visibility", Find("seamark:light:7:visibility"))
            Attribute("8_category", Find("seamark:light:8:category"))
            Attribute("8_character", Find("seamark:light:8:character"))
            Attribute("8_colour", Find("seamark:light:8:colour"))
            Attribute("8_exhibition", Find("seamark:light:8:exhibition"))
            Attribute("8_group", Find("seamark:light:8:group"))
            Attribute("8_height", Find("seamark:light:8:height"))
            Attribute("8_national_information", Find("seamark:light:8:national_information"))
            Attribute("8_period", Find("seamark:light:8:period"))
            Attribute("8_range", Find("seamark:light:8:range"))
            Attribute("8_sector_end", Find("seamark:light:8:sector_end"))
            Attribute("8_sector_start", Find("seamark:light:8:sector_start"))
            Attribute("8_sequence", Find("seamark:light:8:sequence"))
            Attribute("8_vertical_datum", Find("seamark:light:8:vertical_datum"))
            Attribute("8_visibility", Find("seamark:light:8:visibility"))
            Attribute("9_category", Find("seamark:light:9:category"))
            Attribute("9_character", Find("seamark:light:9:character"))
            Attribute("9_colour", Find("seamark:light:9:colour"))
            Attribute("9_exhibition", Find("seamark:light:9:exhibition"))
            Attribute("9_group", Find("seamark:light:9:group"))
            Attribute("9_height", Find("seamark:light:9:height"))
            Attribute("9_multiple", Find("seamark:light:9:multiple"))
            Attribute("9_national_information", Find("seamark:light:9:national_information"))
            Attribute("9_orientation", Find("seamark:light:9:orientation"))
            Attribute("9_period", Find("seamark:light:9:period"))
            Attribute("9_range", Find("seamark:light:9:range"))
            Attribute("9_sector_end", Find("seamark:light:9:sector_end"))
            Attribute("9_sector_start", Find("seamark:light:9:sector_start"))
            Attribute("9_sequence", Find("seamark:light:9:sequence"))
            Attribute("9_vertical_datum", Find("seamark:light:9:vertical_datum"))
            Attribute("9_visibility", Find("seamark:light:9:visibility"))
            Attribute("category", Find("seamark:light:category"))
            Attribute("character", Find("seamark:light:character"))
            Attribute("colour", Find("seamark:light:colour"))
            Attribute("emergency_category", Find("seamark:light:emergency:category"))
            Attribute("emergency_character", Find("seamark:light:emergency:character"))
            Attribute("emergency_colour", Find("seamark:light:emergency:colour"))
            Attribute("emergency_exhibition", Find("seamark:light:emergency:exhibition"))
            Attribute("emergency_group", Find("seamark:light:emergency:group"))
            Attribute("emergency_height", Find("seamark:light:emergency:height"))
            Attribute("emergency_information", Find("seamark:light:emergency:information"))
            Attribute("emergency_period", Find("seamark:light:emergency:period"))
            Attribute("emergency_range", Find("seamark:light:emergency:range"))
            Attribute("emergency_ref", Find("seamark:light:emergency:ref"))
            Attribute("emergency_sequence", Find("seamark:light:emergency:sequence"))
            Attribute("emergency_source", Find("seamark:light:emergency:source"))
            Attribute("emergency_source_date", Find("seamark:light:emergency:source_date"))
            Attribute("emergency_visibility", Find("seamark:light:emergency:visibility"))
            Attribute("exhibition", Find("seamark:light:exhibition"))
            Attribute("group", Find("seamark:light:group"))
            Attribute("height", Find("seamark:light:height"))
            Attribute("information", Find("seamark:light:information"))
            Attribute("multiple", Find("seamark:light:multiple"))
            Attribute("name", Find("seamark:light:name"))
            Attribute("number", Find("seamark:light:number"))
            Attribute("orientation", Find("seamark:light:orientation"))
            Attribute("period", Find("seamark:light:period"))
            Attribute("period_end", Find("seamark:light:period_end"))
            Attribute("period_start", Find("seamark:light:period_start"))
            Attribute("range", Find("seamark:light:range"))
            Attribute("ref", Find("seamark:light:ref"))
            Attribute("referemce", Find("seamark:light:referemce"))
            Attribute("reference", Find("seamark:light:reference"))
            Attribute("sector_end", Find("seamark:light:sector_end"))
            Attribute("sector_start", Find("seamark:light:sector_start"))
            Attribute("sequence", Find("seamark:light:sequence"))
            Attribute("source", Find("seamark:light:source"))
            Attribute("source_date", Find("seamark:light:source_date"))
            Attribute("status", Find("seamark:light:status"))
            Attribute("vertical_datum", Find("seamark:light:vertical_datum"))
            Attribute("vertical_length", Find("seamark:light:vertical_length"))
            Attribute("visibility", Find("seamark:light:visibility"))
            Attribute("name", Find("seamark:name"))
        end,
        ["light_float"] = function()
            Layer("light", false)
            Attribute("type", "light_float")
            Attribute("colour", Find("seamark:light_float:colour"))
            Attribute("colour_pattern", Find("seamark:light_float:colour_pattern"))
            Attribute("system", Find("seamark:light_float:system"))
            Attribute("name", Find("seamark:name"))
        end,
        ["light_major"] = function()
            Layer("light", false)
            Attribute("type", "light_major")
            Attribute("colour", Find("seamark:light_major:colour"))
            Attribute("colour_pattern", Find("seamark:light_major:colour_pattern"))
            Attribute("height", Find("seamark:light_major:height"))
            Attribute("name", Find("seamark:name"))
        end,
        ["light_minor"] = function()
            Layer("light", false)
            Attribute("type", "light_minor")
            Attribute("colour", Find("seamark:light_minor:colour"))
            Attribute("colour_pattern", Find("seamark:light_minor:colour_pattern"))
            Attribute("name", Find("seamark:name"))
        end,
        ["light_vessel"] = function()
            Layer("light", false)
            Attribute("type", "light_vessel")
            Attribute("colour", Find("seamark:light_vessel:colour"))
            Attribute("colour_pattern", Find("seamark:light_vessel:colour_pattern"))
            Attribute("name", Find("seamark:name"))
        end,
        ["lock"] = function()
            Layer("lock", false)
            Attribute("type", "lock")
            Attribute("name", Find("seamark:name"))
        end,
        ["lock_basin"] = function()
            Layer("lock", is_way)
            Attribute("type", "lock_basin")
            Attribute("minimum_depth", Find("seamark:lock_basin:minimum_depth"))
            Attribute("name", Find("seamark:name"))
        end,
        ["marine_farm"] = function()
            Layer("marine", is_way)
            Attribute("type", "marine_farm")
            Attribute("category", Find("seamark:marine_farm:category"))
            Attribute("period_end", Find("seamark:marine_farm:period_end"))
            Attribute("period_start", Find("seamark:marine_farm:period_start"))
            Attribute("restriction", Find("seamark:marine_farm:restriction"))
            Attribute("water_level", Find("seamark:marine_farm:water_level"))
            Attribute("name", Find("seamark:name"))
        end,
        ["military_area"] = function()
            Layer("military_area", is_way)
            Attribute("type", "military_area")
            Attribute("category", Find("seamark:military_area:category"))
            Attribute("restriction", Find("seamark:military_area:restriction"))
            Attribute("name", Find("seamark:name"))
        end,
        ["mooring"] = function()
            Layer("mooring", is_way)
            Attribute("type", "mooring")
            Attribute("category", Find("seamark:mooring:category"))
            Attribute("colour", Find("seamark:mooring:colour"))
            Attribute("colour_pattern", Find("seamark:mooring:colour_pattern"))
            Attribute("condition", Find("seamark:mooring:condition"))
            Attribute("conspicuity", Find("seamark:mooring:conspicuity"))
            Attribute("construction", Find("seamark:mooring:construction"))
            Attribute("period_end", Find("seamark:mooring:period_end"))
            Attribute("period_start", Find("seamark:mooring:period_start"))
            Attribute("reflectivity", Find("seamark:mooring:reflectivity"))
            Attribute("shape", Find("seamark:mooring:shape"))
            Attribute("status", Find("seamark:mooring:status"))
            Attribute("surface", Find("seamark:mooring:surface"))
            Attribute("water_level", Find("seamark:mooring:water_level"))
            Attribute("name", Find("seamark:name"))
        end,
        ["navigation_line"] = function()
            Layer("navigation", false)
            Attribute("type", "navigation_line")
            Attribute("category", Find("seamark:navigation_line:category"))
            Attribute("name", Find("seamark:navigation_line:name"))
            Attribute("orientation", Find("seamark:navigation_line:orientation"))
            Attribute("status", Find("seamark:navigation_line:status"))
            Attribute("name", Find("seamark:name"))
        end,
        ["notice"] = function()
            Layer("notice", false)
            Attribute("type", "notice")
            Attribute("1_addition", Find("seamark:notice:1:addition"))
            Attribute("1_bank", Find("seamark:notice:1:bank"))
            Attribute("1_category", Find("seamark:notice:1:category"))
            Attribute("1_distance_down", Find("seamark:notice:1:distance_down"))
            Attribute("1_distance_end", Find("seamark:notice:1:distance_end"))
            Attribute("1_distance_start", Find("seamark:notice:1:distance_start"))
            Attribute("1_distance_up", Find("seamark:notice:1:distance_up"))
            Attribute("1_function", Find("seamark:notice:1:function"))
            Attribute("1_impact", Find("seamark:notice:1:impact"))
            Attribute("1_information", Find("seamark:notice:1:information"))
            Attribute("1_national_information", Find("seamark:notice:1:national_information"))
            Attribute("1_orientation", Find("seamark:notice:1:orientation"))
            Attribute("1_status", Find("seamark:notice:1:status"))
            Attribute("1_system", Find("seamark:notice:1:system"))
            Attribute("2_addition", Find("seamark:notice:2:addition"))
            Attribute("2_bank", Find("seamark:notice:2:bank"))
            Attribute("2_category", Find("seamark:notice:2:category"))
            Attribute("2_direction", Find("seamark:notice:2:direction"))
            Attribute("2_distance_down", Find("seamark:notice:2:distance_down"))
            Attribute("2_distance_end", Find("seamark:notice:2:distance_end"))
            Attribute("2_distance_start", Find("seamark:notice:2:distance_start"))
            Attribute("2_distance_up", Find("seamark:notice:2:distance_up"))
            Attribute("2_function", Find("seamark:notice:2:function"))
            Attribute("2_impact", Find("seamark:notice:2:impact"))
            Attribute("2_information", Find("seamark:notice:2:information"))
            Attribute("2_national_information", Find("seamark:notice:2:national_information"))
            Attribute("2_orientation", Find("seamark:notice:2:orientation"))
            Attribute("2_status", Find("seamark:notice:2:status"))
            Attribute("2_system", Find("seamark:notice:2:system"))
            Attribute("3_addition", Find("seamark:notice:3:addition"))
            Attribute("3_category", Find("seamark:notice:3:category"))
            Attribute("3_distance_down", Find("seamark:notice:3:distance_down"))
            Attribute("3_distance_end", Find("seamark:notice:3:distance_end"))
            Attribute("3_distance_start", Find("seamark:notice:3:distance_start"))
            Attribute("3_distance_up", Find("seamark:notice:3:distance_up"))
            Attribute("3_function", Find("seamark:notice:3:function"))
            Attribute("3_impact", Find("seamark:notice:3:impact"))
            Attribute("3_information", Find("seamark:notice:3:information"))
            Attribute("3_national_information", Find("seamark:notice:3:national_information"))
            Attribute("3_orientation", Find("seamark:notice:3:orientation"))
            Attribute("3_status", Find("seamark:notice:3:status"))
            Attribute("3_system", Find("seamark:notice:3:system"))
            Attribute("4_addition", Find("seamark:notice:4:addition"))
            Attribute("4_category", Find("seamark:notice:4:category"))
            Attribute("4_distance_down", Find("seamark:notice:4:distance_down"))
            Attribute("4_distance_end", Find("seamark:notice:4:distance_end"))
            Attribute("4_distance_start", Find("seamark:notice:4:distance_start"))
            Attribute("4_distance_up", Find("seamark:notice:4:distance_up"))
            Attribute("4_function", Find("seamark:notice:4:function"))
            Attribute("4_impact", Find("seamark:notice:4:impact"))
            Attribute("4_information", Find("seamark:notice:4:information"))
            Attribute("4_national_information", Find("seamark:notice:4:national_information"))
            Attribute("4_orientation", Find("seamark:notice:4:orientation"))
            Attribute("4_status", Find("seamark:notice:4:status"))
            Attribute("4_system", Find("seamark:notice:4:system"))
            Attribute("5_addition", Find("seamark:notice:5:addition"))
            Attribute("5_category", Find("seamark:notice:5:category"))
            Attribute("5_distance_down", Find("seamark:notice:5:distance_down"))
            Attribute("5_distance_end", Find("seamark:notice:5:distance_end"))
            Attribute("5_distance_start", Find("seamark:notice:5:distance_start"))
            Attribute("5_distance_up", Find("seamark:notice:5:distance_up"))
            Attribute("5_function", Find("seamark:notice:5:function"))
            Attribute("5_impact", Find("seamark:notice:5:impact"))
            Attribute("5_information", Find("seamark:notice:5:information"))
            Attribute("5_orientation", Find("seamark:notice:5:orientation"))
            Attribute("6_addition", Find("seamark:notice:6:addition"))
            Attribute("6_category", Find("seamark:notice:6:category"))
            Attribute("6_distance_down", Find("seamark:notice:6:distance_down"))
            Attribute("6_distance_end", Find("seamark:notice:6:distance_end"))
            Attribute("6_distance_start", Find("seamark:notice:6:distance_start"))
            Attribute("6_distance_up", Find("seamark:notice:6:distance_up"))
            Attribute("6_function", Find("seamark:notice:6:function"))
            Attribute("6_impact", Find("seamark:notice:6:impact"))
            Attribute("6_information", Find("seamark:notice:6:information"))
            Attribute("6_orientation", Find("seamark:notice:6:orientation"))
            Attribute("addition", Find("seamark:notice:addition"))
            Attribute("bank", Find("seamark:notice:bank"))
            Attribute("category", Find("seamark:notice:category"))
            Attribute("channel", Find("seamark:notice:channel"))
            Attribute("direction", Find("seamark:notice:direction"))
            Attribute("distance_down", Find("seamark:notice:distance_down"))
            Attribute("distance_end", Find("seamark:notice:distance_end"))
            Attribute("distance_start", Find("seamark:notice:distance_start"))
            Attribute("distance_up", Find("seamark:notice:distance_up"))
            Attribute("function", Find("seamark:notice:function"))
            Attribute("function_information", Find("seamark:notice:function:information"))
            Attribute("impact", Find("seamark:notice:impact"))
            Attribute("information", Find("seamark:notice:information"))
            Attribute("information_de", Find("seamark:notice:information:de"))
            Attribute("national_information", Find("seamark:notice:national_information"))
            Attribute("orientation", Find("seamark:notice:orientation"))
            Attribute("status", Find("seamark:notice:status"))
            Attribute("system", Find("seamark:notice:system"))
            Attribute("name", Find("seamark:name"))
        end,
        ["obstruction"] = function()
            Layer("obstruction", is_way)
            Attribute("type", "obstruction")
            Attribute("category", Find("seamark:obstruction:category"))
            Attribute("condition", Find("seamark:obstruction:condition"))
            Attribute("depth", Find("seamark:obstruction:depth"))
            Attribute("height", Find("seamark:obstruction:height"))
            Attribute("restriction", Find("seamark:obstruction:restriction"))
            Attribute("status", Find("seamark:obstruction:status"))
            Attribute("surface", Find("seamark:obstruction:surface"))
            Attribute("surface_qualification", Find("seamark:obstruction:surface_qualification"))
            Attribute("vertical_datum", Find("seamark:obstruction:vertical_datum"))
            Attribute("water_level", Find("seamark:obstruction:water_level"))
            Attribute("name", Find("seamark:name"))
        end,
        ["pile"] = function()
            Layer("pile", false)
            Attribute("type", "pile")
            Attribute("category", Find("seamark:pile:category"))
            Attribute("colour", Find("seamark:pile:colour"))
            Attribute("condition", Find("seamark:pile:condition"))
            Attribute("conspicuity", Find("seamark:pile:conspicuity"))
            Attribute("construction", Find("seamark:pile:construction"))
            Attribute("name", Find("seamark:pile:name"))
            Attribute("status", Find("seamark:pile:status"))
            Attribute("vertical_length", Find("seamark:pile:vertical_length"))
            Attribute("water_level", Find("seamark:pile:water_level"))
            Attribute("name", Find("seamark:name"))
        end,
        ["pilot_boarding"] = function()
            Layer("pilot_boarding", false)
            Attribute("type", "pilot_boarding")
            Attribute("category", Find("seamark:pilot_boarding:category"))
            Attribute("channel", Find("seamark:pilot_boarding:channel"))
            Attribute("information", Find("seamark:pilot_boarding:information"))
            Attribute("national_information", Find("seamark:pilot_boarding:national_information"))
            Attribute("name", Find("seamark:name"))
        end,
        ["pipeline_area"] = function()
            Layer("pipeline", is_way)
            Attribute("type", "pipeline_area")
            Attribute("category", Find("seamark:pipeline_area:category"))
            Attribute("product", Find("seamark:pipeline_area:product"))
            Attribute("restriction", Find("seamark:pipeline_area:restriction"))
            Attribute("name", Find("seamark:name"))
        end,
        ["pipeline_overhead"] = function()
            Layer("pipeline", false)
            Attribute("type", "pipeline_overhead")
            Attribute("category", Find("seamark:pipeline_overhead:category"))
            Attribute("clearance_height", Find("seamark:pipeline_overhead:clearance_height"))
            Attribute("product", Find("seamark:pipeline_overhead:product"))
            Attribute("name", Find("seamark:name"))
        end,
        ["pipeline_submarine"] = function()
            Layer("pipeline", false)
            Attribute("type", "pipeline_submarine")
            Attribute("category", Find("seamark:pipeline_submarine:category"))
            Attribute("condition", Find("seamark:pipeline_submarine:condition"))
            Attribute("depth_buried", Find("seamark:pipeline_submarine:depth_buried"))
            Attribute("information", Find("seamark:pipeline_submarine:information"))
            Attribute("name", Find("seamark:pipeline_submarine:name"))
            Attribute("product", Find("seamark:pipeline_submarine:product"))
            Attribute("restriction", Find("seamark:pipeline_submarine:restriction"))
            Attribute("status", Find("seamark:pipeline_submarine:status"))
            Attribute("substance", Find("seamark:pipeline_submarine:substance"))
            Attribute("name", Find("seamark:name"))
        end,
        ["platform"] = function()
            Layer("platform", is_way)
            Attribute("type", "platform")
            Attribute("category", Find("seamark:platform:category"))
            Attribute("colour", Find("seamark:platform:colour"))
            Attribute("colour_pattern", Find("seamark:platform:colour_pattern"))
            Attribute("conspicuity", Find("seamark:platform:conspicuity"))
            Attribute("height", Find("seamark:platform:height"))
            Attribute("product", Find("seamark:platform:product"))
            Attribute("reflectivity", Find("seamark:platform:reflectivity"))
            Attribute("restriction", Find("seamark:platform:restriction"))
            Attribute("status", Find("seamark:platform:status"))
            Attribute("vertical_length", Find("seamark:platform:vertical_length"))
            Attribute("visibility", Find("seamark:platform:visibility"))
            Attribute("name", Find("seamark:name"))
        end,
        ["pole"] = function()
            Layer("pole", false)
            Attribute("type", "pole")
            Attribute("name", Find("seamark:name"))
        end,
        ["precautionary_area"] = function()
            Layer("precautionary_area", is_way)
            Attribute("type", "precautionary_area")
            Attribute("information", Find("seamark:precautionary_area:information"))
            Attribute("restriction", Find("seamark:precautionary_area:restriction"))
            Attribute("name", Find("seamark:name"))
        end,
        ["production_area"] = function()
            Layer("production", is_way)
            Attribute("type", "production_area")
            Attribute("category", Find("seamark:production_area:category"))
            Attribute("condition", Find("seamark:production_area:condition"))
            Attribute("product", Find("seamark:production_area:product"))
            Attribute("restriction", Find("seamark:production_area:restriction"))
            Attribute("name", Find("seamark:name"))
        end,
        ["protected_area"] = function()
            Layer("protected_area", is_way)
            Attribute("type", "protected_area")
            Attribute("name", Find("seamark:name"))
        end,
        ["pylon"] = function()
            Layer("pylon", is_way)
            Attribute("type", "pylon")
            Attribute("category", Find("seamark:pylon:category"))
            Attribute("condition", Find("seamark:pylon:condition"))
            Attribute("construction", Find("seamark:pylon:construction"))
            Attribute("name", Find("seamark:pylon:name"))
            Attribute("status", Find("seamark:pylon:status"))
            Attribute("water_level", Find("seamark:pylon:water_level"))
            Attribute("name", Find("seamark:name"))
        end,
        ["radar_reflector"] = function()
            Layer("radar", false)
            Attribute("type", "radar_reflector")
            Attribute("name", Find("seamark:name"))
        end,
        ["radar_station"] = function()
            Layer("radar", false)
            Attribute("type", "radar_station")
            Attribute("category", Find("seamark:radar_station:category"))
            Attribute("channel", Find("seamark:radar_station:channel"))
            Attribute("conspicuity", Find("seamark:radar_station:conspicuity"))
            Attribute("name", Find("seamark:name"))
        end,
        ["radar_transponder"] = function()
            Layer("radar", false)
            Attribute("type", "radar_transponder")
            Attribute("category", Find("seamark:radar_transponder:category"))
            Attribute("group", Find("seamark:radar_transponder:group"))
            Attribute("height", Find("seamark:radar_transponder:height"))
            Attribute("period", Find("seamark:radar_transponder:period"))
            Attribute("range", Find("seamark:radar_transponder:range"))
            Attribute("sector_end", Find("seamark:radar_transponder:sector_end"))
            Attribute("sector_start", Find("seamark:radar_transponder:sector_start"))
            Attribute("sequence", Find("seamark:radar_transponder:sequence"))
            Attribute("wavelength", Find("seamark:radar_transponder:wavelength"))
            Attribute("name", Find("seamark:name"))
        end,
        ["radio_station"] = function()
            Layer("radio", false)
            Attribute("type", "radio_station")
            Attribute("callsign", Find("seamark:radio_station:callsign"))
            Attribute("category", Find("seamark:radio_station:category"))
            Attribute("channel", Find("seamark:radio_station:channel"))
            Attribute("frequency", Find("seamark:radio_station:frequency"))
            Attribute("group", Find("seamark:radio_station:group"))
            Attribute("mmsi", Find("seamark:radio_station:mmsi"))
            Attribute("name", Find("seamark:radio_station:name"))
            Attribute("range", Find("seamark:radio_station:range"))
            Attribute("name", Find("seamark:name"))
        end,
        ["recommended_route_centreline"] = function()
            Layer("recommended", false)
            Attribute("type", "recommended_route_centreline")
            Attribute("name", Find("seamark:name"))
        end,
        ["recommended_track"] = function()
            Layer("recommended", false)
            Attribute("type", "recommended_track")
            Attribute("category", Find("seamark:recommended_track:category"))
            Attribute("maximum_depth", Find("seamark:recommended_track:maximum_depth"))
            Attribute("minimum_depth", Find("seamark:recommended_track:minimum_depth"))
            Attribute("name", Find("seamark:recommended_track:name"))
            Attribute("orientation", Find("seamark:recommended_track:orientation"))
            Attribute("status", Find("seamark:recommended_track:status"))
            Attribute("traffic_flow", Find("seamark:recommended_track:traffic_flow"))
            Attribute("name", Find("seamark:name"))
        end,
        ["recommended_traffic_lane"] = function()
            Layer("recommended", false)
            Attribute("type", "recommended_traffic_lane")
            Attribute("orientation", Find("seamark:recommended_traffic_lane:orientation"))
            Attribute("name", Find("seamark:name"))
        end,
        ["rescue_station"] = function()
            Layer("rescue", is_way)
            Attribute("type", "rescue_station")
            Attribute("category", Find("seamark:rescue_station:category"))
            Attribute("name", Find("seamark:name"))
        end,
        ["restricted_area"] = function()
            Layer("restricted_area", is_way)
            Attribute("type", "restricted_area")
            Attribute("category", Find("seamark:restricted_area:category"))
            Attribute("information", Find("seamark:restricted_area:information"))
            Attribute("information_en", Find("seamark:restricted_area:information:en"))
            Attribute("maximum_depth", Find("seamark:restricted_area:maximum_depth"))
            Attribute("minimum_depth", Find("seamark:restricted_area:minimum_depth"))
            Attribute("name", Find("seamark:restricted_area:name"))
            Attribute("national_information", Find("seamark:restricted_area:national_information"))
            Attribute("perend", Find("seamark:restricted_area:perend"))
            Attribute("period_end", Find("seamark:restricted_area:period_end"))
            Attribute("period_start", Find("seamark:restricted_area:period_start"))
            Attribute("persta", Find("seamark:restricted_area:persta"))
            Attribute("restriction", Find("seamark:restricted_area:restriction"))
            Attribute("restriction_conditional", Find("seamark:restricted_area:restriction:conditional"))
            Attribute("status", Find("seamark:restricted_area:status"))
            Attribute("surface", Find("seamark:restricted_area:surface"))
            Attribute("name", Find("seamark:name"))
        end,
        ["rock"] = function()
            Layer("rock", is_way)
            Attribute("type", "rock")
            Attribute("category", Find("seamark:rock:category"))
            Attribute("depth", Find("seamark:rock:depth"))
            Attribute("exposition", Find("seamark:rock:exposition"))
            Attribute("quality", Find("seamark:rock:quality"))
            Attribute("status", Find("seamark:rock:status"))
            Attribute("vertical_datum", Find("seamark:rock:vertical_datum"))
            Attribute("water_level", Find("seamark:rock:water_level"))
            Attribute("name", Find("seamark:name"))
        end,
        ["sand_waves"] = function()
            Layer("sand_waves", is_way)
            Attribute("type", "sand_waves")
            Attribute("name", Find("seamark:name"))
        end,
        ["sea_area"] = function()
            Layer("sea", is_way)
            Attribute("type", "sea_area")
            Attribute("category", Find("seamark:sea_area:category"))
            Attribute("restriction", Find("seamark:sea_area:restriction"))
            Attribute("name", Find("seamark:name"))
        end,
        ["seabed"] = function()
            Layer("seabed", is_way)
            Attribute("type", "seabed")
            Attribute("name", Find("seamark:name"))
        end,
        ["seabed_area"] = function()
            Layer("seabed_area", is_way)
            Attribute("type", "seabed_area")
            Attribute("minimum_depth", Find("seamark:seabed_area:minimum_depth"))
            Attribute("quality", Find("seamark:seabed_area:quality"))
            Attribute("surface", Find("seamark:seabed_area:surface"))
            Attribute("surface_qualification", Find("seamark:seabed_area:surface_qualification"))
            Attribute("water_level", Find("seamark:seabed_area:water_level"))
            Attribute("name", Find("seamark:name"))
        end,
        ["seagrass"] = function()
            Layer("seagrass", is_way)
            Attribute("type", "seagrass")
            Attribute("category", Find("seamark:seagrass:category"))
            Attribute("name", Find("seamark:name"))
        end,
        ["seaplane_landing_area"] = function()
            Layer("seaplane_landing_area", is_way)
            Attribute("type", "seaplane_landing_area")
            Attribute("restriction", Find("seamark:seaplane_landing_area:restriction"))
            Attribute("name", Find("seamark:name"))
        end,
        ["separation_boundary"] = function()
            Layer("separation", false)
            Attribute("type", "separation_boundary")
            Attribute("name", Find("seamark:name"))
        end,
        ["separation_crossing"] = function()
            Layer("separation", is_way)
            Attribute("type", "separation_crossing")
            Attribute("name", Find("seamark:name"))
        end,
        ["separation_lane"] = function()
            Layer("separation", false)
            Attribute("type", "separation_lane")
            Attribute("orientation", Find("seamark:separation_lane:orientation"))
            Attribute("name", Find("seamark:name"))
        end,
        ["separation_line"] = function()
            Layer("separation", false)
            Attribute("type", "separation_line")
            Attribute("name", Find("seamark:name"))
        end,
        ["separation_roundabout"] = function()
            Layer("separation", is_way)
            Attribute("type", "separation_roundabout")
            Attribute("name", Find("seamark:name"))
        end,
        ["separation_zone"] = function()
            Layer("separation", is_way)
            Attribute("type", "separation_zone")
            Attribute("category", Find("seamark:separation_zone:category"))
            Attribute("name", Find("seamark:name"))
        end,
        ["shoreline_construction"] = function()
            Layer("shoreline_construction", is_way)
            Attribute("type", "shoreline_construction")
            Attribute("category", Find("seamark:shoreline_construction:category"))
            Attribute("conspicuity", Find("seamark:shoreline_construction:conspicuity"))
            Attribute("construction", Find("seamark:shoreline_construction:construction"))
            Attribute("restriction", Find("seamark:shoreline_construction:restriction"))
            Attribute("status", Find("seamark:shoreline_construction:status"))
            Attribute("water_level", Find("seamark:shoreline_construction:water_level"))
            Attribute("name", Find("seamark:name"))
        end,
        ["signal_station_traffic"] = function()
            Layer("signal", false)
            Attribute("type", "signal_station_traffic")
            Attribute("callsign", Find("seamark:signal_station_traffic:callsign"))
            Attribute("category", Find("seamark:signal_station_traffic:category"))
            Attribute("channel", Find("seamark:signal_station_traffic:channel"))
            Attribute("impact", Find("seamark:signal_station_traffic:impact"))
            Attribute("information", Find("seamark:signal_station_traffic:information"))
            Attribute("name", Find("seamark:signal_station_traffic:name"))
            Attribute("orientation", Find("seamark:signal_station_traffic:orientation"))
            Attribute("name", Find("seamark:name"))
        end,
        ["signal_station_warning"] = function()
            Layer("signal", false)
            Attribute("type", "signal_station_warning")
            Attribute("category", Find("seamark:signal_station_warning:category"))
            Attribute("channel", Find("seamark:signal_station_warning:channel"))
            Attribute("information", Find("seamark:signal_station_warning:information"))
            Attribute("national_information", Find("seamark:signal_station_warning:national_information"))
            Attribute("status", Find("seamark:signal_station_warning:status"))
            Attribute("name", Find("seamark:name"))
        end,
        ["small_craft_facilit"] = function()
            Layer("small", false)
            Attribute("type", "small_craft_facilit")
            Attribute("name", Find("seamark:name"))
        end,
        ["small_craft_facility"] = function()
            Layer("small_craft_facility", false)
            Attribute("type", "small_craft_facility")
            Attribute("category", Find("seamark:small_craft_facility:category"))
            Attribute("information", Find("seamark:small_craft_facility:information"))
            Attribute("name", Find("seamark:name"))
        end,
        ["spring"] = function()
            Layer("spring", false)
            Attribute("type", "spring")
            Attribute("name", Find("seamark:name"))
        end,
        ["sunken_ship"] = function()
            Layer("sunken_ship", false)
            Attribute("type", "sunken_ship")
            Attribute("name", Find("seamark:name"))
        end,
        ["tank"] = function()
            Layer("tank", is_way)
            Attribute("type", "tank")
            Attribute("category", Find("seamark:tank:category"))
            Attribute("colour", Find("seamark:tank:colour"))
            Attribute("conspicuity", Find("seamark:tank:conspicuity"))
            Attribute("name", Find("seamark:name"))
        end,
        ["turning_basin"] = function()
            Layer("turning_basin", is_way)
            Attribute("type", "turning_basin")
            Attribute("clearance_width", Find("seamark:turning_basin:clearance_width"))
            Attribute("minimum_depth", Find("seamark:turning_basin:minimum_depth"))
            Attribute("name", Find("seamark:name"))
        end,
        ["vehicle_transfer"] = function()
            Layer("vehicle_transfer", is_way)
            Attribute("type", "vehicle_transfer")
            Attribute("name", Find("seamark:name"))
        end,
        ["water_turbulence"] = function()
            Layer("water_turbulence", is_way)
            Attribute("type", "water_turbulence")
            Attribute("category", Find("seamark:water_turbulence:category"))
            Attribute("name", Find("seamark:name"))
        end,
        ["waterway_gauge"] = function()
            Layer("waterway_gauge", is_way)
            Attribute("type", "waterway_gauge")
            Attribute("category", Find("seamark:waterway_gauge:category"))
            Attribute("colour", Find("seamark:waterway_gauge:colour"))
            Attribute("orientation", Find("seamark:waterway_gauge:orientation"))
            Attribute("reference", Find("seamark:waterway_gauge:reference"))
            Attribute("name", Find("seamark:name"))
        end,
        ["weed"] = function()
            Layer("weed", is_way)
            Attribute("type", "weed")
            Attribute("category", Find("seamark:weed:category"))
            Attribute("name", Find("seamark:name"))
        end,
        ["wreck"] = function()
            Layer("wreck", is_way)
            Attribute("type", "wreck")
            Attribute("category", Find("seamark:wreck:category"))
            Attribute("conspicuity", Find("seamark:wreck:conspicuity"))
            Attribute("depth", Find("seamark:wreck:depth"))
            Attribute("information", Find("seamark:wreck:information"))
            Attribute("reflectivity", Find("seamark:wreck:reflectivity"))
            Attribute("restriction", Find("seamark:wreck:restriction"))
            Attribute("status", Find("seamark:wreck:status"))
            Attribute("water_level", Find("seamark:wreck:water_level"))
            Attribute("name", Find("seamark:name"))
        end,
    }

    if handlers[type] then
        handlers[type]()
    end
end

function node_function()
    process_seamark(false)
end

function way_function()
    process_seamark(true)
end